### ISSUE TITLE
ts_gui example build error

### ISSUE THREAD

**Issue by dboris** [janestreet/incr_dom#4] opened 2018-07-24 20:51 UTC
```
$ dune build example/ts_gui/{main.bc.js,index.html}
File "src/arg_spec.ml", line 55, characters 15-21: Assertion failed
Backtrace:
Raised at file "src/dep_path.ml" (inlined), line 45, characters 24-55
Called from file "src/build_system.ml", line 186, characters 6-48
Called from file "src/fiber/fiber.ml", line 243, characters 6-18
Error: Conflict between the following libraries:
- "incr_dom" in _build/default/src
- "incr_dom" in /Users/boris/.opam/ocsigen/lib/incr_dom
    -> required by library "incr_dom_widgets" in /Users/boris/.opam/ocsigen/lib/incr_dom_widgets
This is not allowed.
```

Here are the lib versions I have installed:
```
incr_dom                            v0.11.0  A library for building dynamic weba
incr_dom_widgets                    v0.11.0  A library of libraries and widgets 
incr_map                            v0.11.0  Helpers for incremental operations 
incr_select                         v0.11.0  Handling of large set of incrementa
incremental                         v0.11.0  Library for incremental computation
incremental_kernel                  v0.11.1  Library for incremental computation
```

**Comment by ghost** [comment] 2018-07-31 10:04
Yes, that's a known issue. If you want to build the examples, you have to create a single dune workspace containing incr_dom and its transitive dependencies. The [duniverse tool](https://github.com/avsm/duniverse) may be helpful for that

**Comment by TyOverby** [comment] 2020-05-27 18:51
Closing due to how old the issue is.  If you still have problems getting it installed, please feel free to re-open or create a new issue.

**Closed as completed by TyOverby** 2020-05-27 18:51 UTC
Labels: forwarded-to-js-devs
